//Hanna
// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc.team4930.robot;
    
import edu.wpi.first.wpilibj.*;

import edu.wpi.first.wpilibj.livewindow.LiveWindow;
import java.util.Vector;

/**
 * The RobotMap is a mapping from the ports sensors and actuators are wired into
 * to a variable name. This provides flexibility changing wiring, makes checking
 * the wiring easier and significantly reduces the number of magic numbers
 * floating around.
 */
public class RobotMap {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    public static SpeedController driveTrainPWM0;      //defining PWM 0 as on the drive train
    //public static SpeedController driveTrainPWM1;    //PWM 0 no longer in use on the robot, line defining PWM 0 commented out
    //public static SpeedController driveTrainPWM8;    //PWM 8 no longer in use on the robot, line defining PWM 8 commented out
    public static SpeedController driveTrainPWM9;      //defining PWM 9 as on the drive train
    public static RobotDrive driveTrainRobotDrive;     //drive variable
    public static SpeedController intakePWM4;          //defining PWM 4 as for intake
    public static SpeedController intakePWM5;          //defining PWM 5 as for intake
    public static SpeedController elevatorPWM3;        //defining PWM 3 as for the elevator
    public static SpeedController elevatorPWM6;        //defining PWM 6 as for the elevator
    public static SpeedController armPWM2;             //defining PWM 2 as for the arm
    public static SpeedController armPWM7;			   //defining PWm 7 as for the arm
    public static Encoder encodersLeftDriveTrain;
    public static Encoder encodersRightDriveTrain;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    public static void init() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        driveTrainPWM0 = new TalonSRX(0);			   //assigning talon 0 to PWM 0
        LiveWindow.addActuator("DriveTrain", "PWM0", (TalonSRX) driveTrainPWM0);
        
       // driveTrainPWM1 = new TalonSRX(1);            //lines commented out because PWM 1 no longer in use on robot
       //LiveWindow.addActuator("DriveTrain", "PWM1", (TalonSRX) driveTrainPWM1);
        
        //driveTrainPWM8 = new TalonSRX(8);            //lines commented out becuase PWM 8 no longer in use on robot
        //LiveWindow.addActuator("DriveTrain", "PWM8", (TalonSRX) driveTrainPWM8);
        
        driveTrainPWM9 = new TalonSRX(9);              //assigning talon 9 to PWM 9
        LiveWindow.addActuator("DriveTrain", "PWM9", (TalonSRX) driveTrainPWM9);
        
        driveTrainRobotDrive = new RobotDrive(driveTrainPWM0, driveTrainPWM9); //new RobotDrive with 2 motors
        
        driveTrainRobotDrive.setSafetyEnabled(true);
        driveTrainRobotDrive.setExpiration(0.1);       
        driveTrainRobotDrive.setSensitivity(0.5);      //sets sensitivity at 0.5
        driveTrainRobotDrive.setMaxOutput(1.0);        //set 1 as the max output, range is -1 to 1
        //driveTrainRobotDrive.setInvertedMotor(RobotDrive.MotorType.kFrontLeft, true);
        //driveTrainRobotDrive.setInvertedMotor(RobotDrive.MotorType.kRearLeft, true);
        //driveTrainRobotDrive.setInvertedMotor(RobotDrive.MotorType.kFrontRight, true);
        //driveTrainRobotDrive.setInvertedMotor(RobotDrive.MotorType.kRearRight, true);
        intakePWM4 = new TalonSRX(4);                  //assigning talon 4 to PWM 4
        LiveWindow.addActuator("Intake", "PWM4", (TalonSRX) intakePWM4);
        
        intakePWM5 = new TalonSRX(5);                  //assigning talon 5 to PWM 5
        LiveWindow.addActuator("Intake", "PWM5", (TalonSRX) intakePWM5);
        
        elevatorPWM3 = new TalonSRX(3);                //assigning talon 3 to PWM 3
        LiveWindow.addActuator("Elevator", "PWM3", (TalonSRX) elevatorPWM3);
        
        elevatorPWM6 = new TalonSRX(6);                //assigning talon 6 to PWM 6
        LiveWindow.addActuator("Elevator", "PWM6", (TalonSRX) elevatorPWM6);
        
        armPWM2 = new TalonSRX(2);                     //assigning talon 2 to PWM 2
        LiveWindow.addActuator("Arm", "PWM2", (TalonSRX) armPWM2);
        
        armPWM7 = new TalonSRX(7);                     //assigning talon 7 to PWM 7
        LiveWindow.addActuator("Arm", "PWM7", (TalonSRX) armPWM7);
        

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    }
}