//Thomas Kubiniec
// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc.team4930.robot.subsystems;

import org.usfirst.frc.team4930.robot.RobotMap;
import org.usfirst.frc.team4930.robot.commands.*;
import edu.wpi.first.wpilibj.*;

import edu.wpi.first.wpilibj.command.Subsystem;


/**
 *
 */
public class DriveTrain extends Subsystem {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	//These are the declarations of each speedController, telling them to allocate to each of the DriveTrain Motors
	//in PMW ports 0,1,8 and 9.
    SpeedController pWM0 = RobotMap.driveTrainPWM0;
//    SpeedController pWM1 = RobotMap.driveTrainPWM1;
//    SpeedController pWM8 = RobotMap.driveTrainPWM8;
    SpeedController pWM9 = RobotMap.driveTrainPWM9;
    RobotDrive robotDrive = RobotMap.driveTrainRobotDrive;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    
    // Put methods for controlling this subsystem
    // here. Call these from Commands.

    public void initDefaultCommand() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
        setDefaultCommand(new TeleOpTankDrive());

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
	
        // Set the default command for a subsystem here.
        //setDefaultCommand(new MySpecialCommand());
    }
    
    public void takeJoystickInputs(Joystick left, Joystick right){
    	robotDrive.tankDrive(-left.getY(), -right.getY(), true);
    }
    
    public void runMotors(double left, double right){
    	robotDrive.tankDrive(-left, -right);
    }
    
    public void stop() {
    	robotDrive.tankDrive(0, 0);
    }
    
}